name = input("Enter First and Last Name: ")
countryOfOrigin = input("Enter Country of Origin: ")
currentJob = input("Enter your Current Job: ")
email = input("Enter Email Address: ")
phone = input("Enter Phone Number: ")
city = input("Enter Current City: ")
mailingAddress = input("Enter Mailing Address: ")

print("=================================================")
print("Name: " + name)
print("Country: " + countryOfOrigin)
print("Profession: " + currentJob)
print("Email: " + email)
print("Phone: " + phone)
print("City: " + city)
print("Address: " + mailingAddress)
print("=================================================")